version: "3.3"
services:
  purchase_orders_api:
    container_name: purchase_orders_api_${ENV}
    image: ${PURCHASE_ORDERS_SERVICE_IMAGE}
    profiles:
      - purchase_orders_api
      - all
    ports:
    - "5000"
    restart: always
    environment:
      - SERVICE_NAME=purchase_orders_api
    networks:
      - purchase_orders
      - domain

networks:
  purchase_orders:
    name: purchase_orders_api_${ENV}
    internal: true
  domain:
    name: sales_${ENV}
    external: true