.tags_service_variables: &tags_service_variables
  SERVICE_NAME: "tags_api"
  SERVICE_PATH: "services/tags_service"

build_tags_service:
  extends: .build_service
  variables: *tags_service_variables

deliver_tags_dockerhub:
  extends: .deliver_dockerhub
  variables: *tags_service_variables
  needs:
    - job: build_tags_service
      artifacts: true