build_tags_service:
  stage: build
  tags:
    - dev
  variables:
    SERVICE_NAME: "tags_api"
    SERVICE_PATH: "services/tags_service"
  rules:
    - !reference [.rule_run_if_new_changes, rules]  
  before_script:
    - !reference [.create_and_export_service_images_variables]
  script:
    - docker build -t ${PROD_IMAGE} -f ${SERVICE_PATH}/tags_api/Dockerfile.prod ${SERVICE_PATH}/tags_api
    - !reference [.login_to_gitlab_registry]
    - docker push ${PROD_IMAGE}
  needs:
    - job: preparation
      artifacts: true
