.frontend_domain_variables: &frontend_domain_variables
  DOMAIN_PATH: "frontend"
  SERVICE_NAME: "frontend"
  SERVICE_PATH: "frontend/quickcart_frontend"

build_frontend:
  extends: .build_service
  variables: *frontend_domain_variables
  script:
    - !reference [.build_gitlab_prod_image]
    - !reference [.login_to_gitlab_registry]
    - !reference [.push_gitlab_prod_image]

deploy_qa_frontend:
  extends: .deploy_qa
  variables: *frontend_domain_variables
  needs:
    - job: build_frontend
      artifacts: true
    - job: deploy_qa_api_gateway
      artifacts: false
      optional: true

deliver_frontend_dockerhub:
  extends: .deliver_dockerhub
  variables: *frontend_domain_variables
  needs:
    - job: build_frontend
      artifacts: true
    - job: deploy_qa_frontend
      artifacts: false

deploy_prod_frontend:
  extends: .deploy_prod
  variables: *frontend_domain_variables
  needs:
    - job: deliver_frontend_dockerhub
      artifacts: false
      optional: true
    - job: deploy_prod_api_gateway
      artifacts: false
      optional: true
