.frontend_domain_variables: &frontend_domain_variables
  DOMAIN_PATH: "frontend"
  SERVICE_NAME: "frontend"
  SERVICE_PATH: "frontend/src"

build_frontend:
  extends: .build_service
  variables: *frontend_domain_variables

deploy_qa_frontend:
  extends: .deploy_qa
  variables: *frontend_domain_variables
  needs:
    - job: build_frontend
      artifacts: true
    - job: deploy_qa_api_gateway_service
      artifacts: false
      optional: true

deliver_frontend_dockerhub:
  extends: .deliver_dockerhub
  variables: *frontend_domain_variables
  needs:
    - job: build_frontend
      artifacts: true
    - job: deploy_qa_frontend
      artifacts: false

deploy_prod_frontend:
  extends: .deploy_prod
  variables: *frontend_domain_variables
  needs:
    - job: deliver_frontend_dockerhub
      artifacts: false
      optional: true
    - job: deploy_prod_api_gateway_domain
      artifacts: false
      optional: true
