FROM node:16-alpine as builder

WORKDIR /app
COPY ./package.json ./
COPY ./package-lock.json ./
RUN npm install --frozen-lockfile

COPY . .
RUN npm run build

FROM nginx:1.21.0-alpine
RUN mkdir /var/www/
COPY --from=builder /app/build /var/www/build
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

HEALTHCHECK CMD curl -f http://localhost:80 || exit 1

EXPOSE 80

