version: "3.3"
services:
  frontend:
    container_name: frontend_${ENV}
    image: "${FRONTEND_IMAGE}"
    profiles:
      - all
      - frontend
    restart: always
    environment:
      - ENV=${ENV}
      - SERVICE_NAME=frontend
    ports:
      - "80"
    networks:
      - services
      - frontend
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:80" ]
      interval: 4s
      timeout: 5s
      start_period: 10s
      retries: 5

networks:
  services:
    name: services_${ENV}
    external: true
  frontend:
    name: frontend_${ENV}
    external: true
