.shopping_cart_service_variables: &shopping_cart_service_variables
  SERVICE_NAME: "shopping_cart_api"
  SERVICE_PATH: "services/shopping_cart_service"

build_shopping_cart_service:
  extends: .build_service
  variables: *shopping_cart_service_variables

deliver_shopping_cart_dockerhub:
  extends: .deliver_dockerhub
  variables: *shopping_cart_service_variables
