stages:
  - prep
  - build
  - test
  - deliver
  - deploy

default:
  image: docker:24.0.1

variables:
  GITLAB_IMAGE_BASE: "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
  DOCKERHUB_IMAGE_BASE: "$DOCKERHUB_USER"

preparation:
  stage: prep
  tags:
    - dev
  script:
    - export BUILD_ID=$(date +%Y%m%d%H%M)
    - echo "BUILD_ID=${BUILD_ID}" > context.env
  artifacts:
    reports:
      dotenv: context.env

include:
  - "/.utils_ci.yml"
  - "services/*_service/*_ci.yml"
# deploy-prod:
#   stage: deploy
#   tags:
#     - prod
#   script:
#     - export API_IMAGE=$DOCKERHUB_API_IMAGE
#     # - export CLIENT_IMAGE=$DOCKERHUB_CLIENT_IMAGE

#     - docker login -u $DOCKERHUB_USER --password $DOCKERHUB_PASS

#     - docker compose -f docker-compose.yml stop
#     - docker compose -f docker-compose.yml rm
#     - docker compose -f docker-compose.yml pull
#     - docker compose -f docker-compose.yml up -d
#   needs:
#     - job: deliver-dockerhub
#     - job: preparation
#       artifacts: true
