stages:
  - prep
  - build
  # - test
  - deliver
  - deploy

default:
  image: docker:24.0.1

variables:
  GITLAB_IMAGE_BASE: "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
  DOCKERHUB_IMAGE_BASE: "$DOCKERHUB_USER"

preparation:
  stage: prep
  tags:
    - dev
  script:
    - export BUILD_ID=$(date +%Y%m%d%H%M)
    - echo "BUILD_ID=${BUILD_ID}" > context.env
    - echo "BUILD_ID2=${BUILD_ID}" > context.env
    - curl -L "https://gitlab.com/api/v4/projects/45992281/jobs/artifacts/main/raw/context.env?job=preparation" --output file.out
  artifacts:
    reports:
      dotenv: context.env
    paths:
      - context.env
      - file.out

include:
  - "/.utils_ci.yml"
  - "*/**/*_ci.yml"
  
