stages:
  - prep
  - build
  - test
  - deliver
  - deploy

default:
  image: docker:24.0.1

variables:
  GITLAB_IMAGE_BASE: "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
  GITLAB_JOB_ARTIFACTS_BASE: "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/raw"
  DOCKERHUB_IMAGE_BASE: "$DOCKERHUB_USER"

preparation:
  stage: prep
  tags:
    - dev
  script:
    - export BUILD_ID=$(date +%Y%m%d%H%M)
    - echo "BUILD_ID=${BUILD_ID}" > context.env
  artifacts:
    reports:
      dotenv: context.env

include:
  - "/.utils_ci.yml"
  - "*/*_ci.yml"
