stages:
  - prep
  - build
  - test
  - prep_qa
  - qa
  - deliver
  - prep_deploy
  - deploy

default:
  image: docker:24.0.1

variables:
  GITLAB_IMAGE_BASE: "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
  DOCKERHUB_IMAGE_BASE: "$DOCKERHUB_USER"

include:
  - "/.utils_ci.yml"
  - "*/**/*_ci.yml"
  - "**/*_ci.yml"

preparation:
  extends: .preparation
