.create_and_export_service_images_variables:
  - export GITLAB_${SERVICE_NAME}_PROD_IMAGE=${GITLAB_IMAGE_BASE}/${SERVICE_NAME}:prod-${BUILD_ID}
  - echo "GITLAB_${SERVICE_NAME}_PROD_IMAGE=${GITLAB_IMAGE_BASE}/${SERVICE_NAME}:prod-${BUILD_ID}" >> context.env
  - export DOCKER_HUB_${SERVICE_NAME}_PROD_IMAGE=${DOCKER_IMAGE_BASE}/${SERVICE_NAME}:prod-${BUILD_ID}
  - echo "DOCKER_HUB_${SERVICE_NAME}_PROD_IMAGE=${DOCKER_IMAGE_BASE}/${SERVICE_NAME}:prod-${BUILD_ID}" >> context.env
  - eval "PROD_IMAGE=\${GITLAB_${SERVICE_NAME}_PROD_IMAGE}"

.login_to_gitlab_registry:
  - docker login -u $CI_REGISTRY_USER --password $CI_JOB_TOKEN $CI_REGISTRY

.login_to_dockerhub_registry:
  - docker login -u $DOCKER_HUB_USER --password $DOCKER_HUB_PASS

.rule_run_if_push_changes:
  - rules:
      - if: $CI_PIPELINE_SOURCE == "push" #default
        when: on_success #default
        changes:
          paths:
            - $SERVICE_PATH/**
