.auth_service_variables: &auth_service_variables
  SERVICE_NAME: "auth_api"
  SERVICE_PATH: "users/auth_service"

build_auth_service:
  extends: .build_service
  variables: *auth_service_variables

test_auth_service:
  extends: .test_service
  needs:
    - job: build_auth_service
      artifacts: true

deliver_auth_dockerhub:
  extends: .deliver_dockerhub
  variables: *auth_service_variables
  needs:
    - job: build_auth_service
      artifacts: true
    - job: test_auth_service
      artifacts: false
