.auth_service_variables: &auth_service_variables
  SERVICE_NAME: "auth_api"
  SERVICE_PATH: "users/auth_service"

build_auth_service:
  extends: .build_service
  variables: *auth_service_variables
  script:
    - echo Trying wget
    # - wget -O tags_env ${GITLAB_JOB_ARTIFACTS_BASE}/context.env?job=build_tags_service&job_token=$CI_JOB_TOKEN"
    # - cat tags_env

# test_auth_service:
#   extends: .test_service
#   needs:
#     - job: build_auth_service
#       artifacts: true

# deliver_auth_dockerhub:
#   extends: .deliver_dockerhub
#   variables: *auth_service_variables
#   needs:
#     - job: build_auth_service
#       artifacts: true
#     - job: test_auth_service
#       artifacts: false

# deploy_auth_prod:
#   extends: .deploy_prod
#   variables: *auth_service_variables
#   needs:
#     - job: deliver_auth_dockerhub
#       artifacts: false
#     - job: build_auth_service
#       artifacts: true
