.auth_service_variables: &auth_service_variables
  DOMAIN_PATH: "users"
  SERVICE_PATH: "users/auth_service"
  SERVICE_NAME: "auth_api"

build_auth_service:
  extends: .build_service
  variables: *auth_service_variables

test_auth_service:
  extends: .test_service
  variables: *auth_service_variables
  needs:
    - job: build_auth_service
      artifacts: true

deliver_auth_dockerhub:
  extends: .deliver_dockerhub
  variables: *auth_service_variables
  needs:
    - job: build_auth_service
      artifacts: true
    - job: test_auth_service
      artifacts: false
