.categories_service_variables: &categories_service_variables
  DOMAIN_PATH: "products"
  SERVICE_PATH: "products/categories_service"
  SERVICE_NAME: "categories_api"

build_categories_service:
  extends: .build_service
  variables: *categories_service_variables

test_categories_service:
  extends: .test_service
  variables: *categories_service_variables
  needs:
    - job: build_categories_service
      artifacts: true

deliver_categories_dockerhub:
  extends: .deliver_dockerhub
  variables: *categories_service_variables
  needs:
    - job: build_categories_service
      artifacts: true
    - job: test_categories_service
      artifacts: false