.api_gateway_domain_variables: &api_gateway_domain_variables
  DOMAIN_PATH: "api_gateway"
  SERVICE_NAME: "api_gateway"
  SERVICE_PATH: "api_gateway"

build_api_gateway_service:
  extends: .build_service
  variables: *api_gateway_domain_variables
  script:
    - !reference [.build_gitlab_prod_image]
    - !reference [.login_to_gitlab_registry]
    - !reference [.push_gitlab_prod_image]

deliver_api_gateway_dockerhub:
  extends: .deliver_dockerhub
  variables: *api_gateway_domain_variables
  # needs:
    # - job: build_api_gateway_service
      # artifacts: true

deploy_prod_api_gateway:
  stage: deploy
  tags:
    - prod
  extends: .deploy_api_gateway
  variables:
    ENV: prod
    <<: *api_gateway_domain_variables
  needs:
    - job: deliver_api_gateway_dockerhub
      artifacts: false

deploy_qa_api_gateway:
  stage: qa
  tags:
    - qa
  extends: .deploy_api_gateway
  variables:
    ENV: qa
    <<: *api_gateway_domain_variables
  needs:
    - job: deliver_api_gateway_dockerhub
      artifacts: false
