.api_gateway_domain_variables: &api_gateway_domain_variables
  DOMAIN_PATH: "api_gateway"

deploy_prod_api_gateway:
  stage: deploy
  tags:
    - prod
  extends: .deploy_api_gateway
  variables:
    ENV: prod
    <<: *api_gateway_domain_variables

deploy_qa_api_gateway:
  stage: qa
  tags:
    - qa
  extends: .deploy_api_gateway
  variables:
    ENV: qa
    <<: *api_gateway_domain_variables