.api_gateway_domain_variables: &api_gateway_domain_variables
  DOMAIN_PATH: "api_gateway"
  SERVICE_NAME: "api_gateway"
  SERVICE_PATH: "api_gateway"

build_api_gateway:
  extends: .build_service
  variables: *api_gateway_domain_variables
  script:
    - !reference [.build_gitlab_prod_image]
    - !reference [.login_to_gitlab_registry]
    - !reference [.push_gitlab_prod_image]

deploy_qa_api_gateway:
  extends: .deploy_qa
  variables: *api_gateway_variables
  needs:
    - job: build_api_gateway
      artifacts: true
    - job: test_api_gateway
      artifacts: false
  
test_integration_and_functional_api_gateway:
  extends: .test_integration_and_functional_service
  variables: *api_gateway_variables
  needs:
    - job: build_api_gateway
      artifacts: true
    - job: deploy_qa_api_gateway
      artifacts: false
  
deliver_api_gateway_dockerhub:
  extends: .deliver_dockerhub
  variables: *api_gateway_domain_variables
  needs:
    - job: build_api_gateway
      artifacts: true

deploy_prod_api_gateway:
  extends: .deploy_prod
  needs:
    - job: deliver_api_gateway_dockerhub
      artifacts: false
      optional: true
