version: "3.3"
services:
  api_gateway_test:
    container_name: api_gateway_test_integration
    image: "${API_GATEWAY_IMAGE}"
    profiles:
      - api_gateway
    restart: always
    environment:
      - ENV=${ENV}
      - SERVICE_NAME=api_gateway
    networks:
      - services

networks:
  services:
    name: services_${ENV}
    external: true
