version: "3.3"
services:
  api_gateway:
    container_name: api_gateway_api_${ENV}
    image: "${API_GATEWAY_IMAGE}"
    restart: always
    ports:
      - "80"
    networks:
      - services

networks:
  services:
    name: services_${ENV}
    external: true
