# Use Python 3.9 base image
FROM python:3.9 

# Create a non-root user for the container
RUN groupadd -g 999 python \
    && useradd -r -u 999 -g python python \
    && mkdir -p /usr/app \
    && python -m venv /usr/app/.venv \
    && chown -R python:python /usr/app

ENV PATH="/usr/app/.venv/bin:$PATH"
ENV PIP_NO_CACHE_DIR=off

# Set the working directory for the container
WORKDIR /usr/app

# Add and install requirements
COPY --chown=python:python requirements.test.txt ./requirements.test.txt
RUN  python -m pip install -r ./requirements.test.txt

# Add app
COPY --chown=python:python tests ./tests

# Add entrypoint.sh
COPY --chown=python:python test.sh .
RUN chmod +x /usr/app/test.sh

# CMD ["./test.sh"]

CMD exit 1