.reviews_service_variables: &reviews_service_variables
  DOMAIN_PATH: "products"
  SERVICE_PATH: "products/reviews_service"
  SERVICE_NAME: "reviews_api"

build_reviews_service:
  extends: .build_service
  variables: *reviews_service_variables

test_reviews_service:
  extends: .test_service
  needs:
    - job: build_reviews_service
      artifacts: true

deliver_reviews_dockerhub:
  extends: .deliver_dockerhub
  variables: *reviews_service_variables
  needs:
    - job: build_reviews_service
      artifacts: true
    - job: test_reviews_service
      artifacts: false