.reviews_service_variables: &reviews_service_variables
  DOMAIN_PATH: "products"
  SERVICE_PATH: "products/reviews_service"
  SERVICE_NAME: "reviews_api"

build_reviews_service:
  extends: .build_service
  variables: *reviews_service_variables

test_reviews_service:
  extends: .test_service
  variables: *reviews_service_variables
  needs:
    - job: build_reviews_service
      artifacts: true

deploy_qa_reviews_service:
  extends: .deploy_qa
  variables: *reviews_service_variables
  needs:
    - job: build_reviews_service
      artifacts: true
    - job: test_reviews_service
      artifacts: false

test_integration_and_functional_reviews_service:
  extends: .test_integration_and_functional_service
  variables: *reviews_service_variables
  needs:
    - job: build_reviews_service
      artifacts: true
    - job: deploy_qa_reviews_service
      artifacts: false
    - job: deploy_qa_products_service
      artifacts: false
    - job: deploy_qa_users_service
      artifacts: false
    - job: deploy_qa_purchase_orders_service
      artifacts: false
    - job: deploy_qa_api_gateway
      artifacts: false
      
deliver_reviews_dockerhub:
  extends: .deliver_dockerhub
  variables: *reviews_service_variables
  needs:
    - job: build_reviews_service
      artifacts: true
    - job: test_integration_and_functional_reviews_service
      artifacts: false