.products_service_variables: &products_service_variables
  SERVICE_NAME: "products_api"
  SERVICE_PATH: "services/products_service"

build_products_service:
  extends: .build_service
  variables: *products_service_variables

deliver_products_dockerhub:
  extends: .deliver_dockerhub
  variables: *products_service_variables
