.shopping_cart_service_variables: &shopping_cart_service_variables
  DOMAIN_PATH: "users"
  SERVICE_PATH: "users/shopping_cart_service"
  SERVICE_NAME: "shopping_cart_api"

build_shopping_cart_service:
  extends: .build_service
  variables: *shopping_cart_service_variables

test_shopping_cart_service:
  extends: .test_service
  variables: *shopping_cart_service_variables
  needs:
    - job: build_shopping_cart_service
      artifacts: true

deliver_shopping_cart_dockerhub:
  extends: .deliver_dockerhub
  variables: *shopping_cart_service_variables
  needs:
    - job: build_shopping_cart_service
      artifacts: true
    - job: test_shopping_cart_service
      artifacts: false
