.shopping_cart_service_variables: &shopping_cart_service_variables
  SERVICE_NAME: "shopping_cart_api"
  SERVICE_PATH: "users/shopping_cart_service"

build_shopping_cart_service:
  extends: .build_service
  variables: *shopping_cart_service_variables

test_shopping_cart_service:
  extends: .test_service
  needs:
    - job: build_shopping_cart_service
      artifacts: true

deliver_shopping_cart_dockerhub:
  extends: .deliver_dockerhub
  variables: *shopping_cart_service_variables
  needs:
    - job: build_shopping_cart_service
      artifacts: true

deploy_shopping_cart_prod:
  extends: .deploy_prod
  variables: *shopping_cart_service_variables
  needs:
    - job: deliver_shopping_cart_dockerhub
      artifacts: false
    - job: build_shopping_cart_service
      artifacts: true
