.auth_service_variables: &auth_service_variables
  SERVICE_NAME: "auth_api"
  SERVICE_PATH: "services/auth_service"

.set_images_names: &set_images_names
  - eval "GITLAB_PROD_IMAGE=\${GITLAB_${SERVICE_NAME}_PROD_IMAGE}"
  - eval "DOCKER_HUB_PROD_IMAGE=\${GITLAB_${SERVICE_NAME}_PROD_IMAGE}"

build_auth_service:
  stage: build
  tags:
    - dev
  variables: *auth_service_variables
  rules:
    - !reference [.rule_run_if_new_changes, rules]
  before_script:
    - !reference [.create_and_export_service_images_variables]
    - *set_images_names
  script:
    - docker build -t ${GITLAB_PROD_IMAGE} -f ${SERVICE_PATH}/auth_api/Dockerfile.prod ${SERVICE_PATH}/auth_api
    - !reference [.login_to_gitlab_registry]
    - docker push ${GITLAB_PROD_IMAGE}
  artifacts:
    reports:
      dotenv: context.env
  needs:
    - job: preparation
      artifacts: true

deliver_auth_dockerhub:
  stage: deliver
  tags:
    - dev
  variables: *auth_service_variables
  rules:
    - !reference [.rule_run_if_new_changes, rules]
  before_script:
    - *set_images_names
  script:
    - !reference [.login_to_gitlab_registry]
    - !reference [.login_to_dockerhub_registry]
    - docker tag $GITLAB_PROD_IMAGE $DOCKER_HUB_PROD_IMAGE
    - docker push $DOCKER_HUB_PROD_IMAGE
  needs:
    - job: preparation
      artifacts: true
    - job: build_auth_service
      artifacts: true
