build_auth_service:
  stage: build
  tags:
    - dev
  variables:
    SERVICE_NAME: "auth_api"
    SERVICE_PATH: "services/auth_service"
  rules:
    # - !reference [.rule_run_if_push_changes, rules]
  before_script:
    - !reference [.create_and_export_service_images_variables]
  script:
    - docker build -t ${PROD_IMAGE} -f ${SERVICE_PATH}/auth_api/Dockerfile.prod ${SERVICE_PATH}/auth_api
    - !reference [.login_to_gitlab_registry]
    - docker push ${PROD_IMAGE}
  needs:
    - job: preparation
      artifacts: true
