build_product_coordinator_service:
  stage: build
  tags:
    - dev
  variables:
    SERVICE_NAME: "product_coordinator_api"
    SERVICE_PATH: "services/product_coordinator_service"
  rules:
    - !reference [.rule_run_if_new_changes, rules] 
  before_script:
    - !reference [.create_and_export_service_images_variables]
  script:
    - docker build -t ${PROD_IMAGE} -f ${SERVICE_PATH}/product_coordinator_api/Dockerfile.prod ${SERVICE_PATH}/product_coordinator_api
    - !reference [.login_to_gitlab_registry]
    - docker push ${PROD_IMAGE}
  # artifacts:
  #   reports:
  #     dotenv: context.env
  needs:
    - job: preparation
      artifacts: true
