.product_coordinator_service_variables: &product_coordinator_service_variables
  SERVICE_NAME: "product_coordinator_api"
  SERVICE_PATH: "services/product_coordinator_service"

build_product_coordinator_service:
  extends: .build_service
  variables: *product_coordinator_service_variables

deliver_product_coordinator_dockerhub:
  extends: .deliver_dockerhub
  variables: *product_coordinator_service_variables
