.purchase_orders_service_variables: &purchase_orders_service_variables
  DOMAIN_PATH: "sales"
  SERVICE_PATH: "sales/purchase_orders_service"
  SERVICE_NAME: "purchase_orders_api"

build_purchase_orders_service:
  extends: .build_service
  variables: *purchase_orders_service_variables

test_purchase_orders_service:
  extends: .test_service
  needs:
    - job: build_purchase_orders_service
      artifacts: true

deliver_purchase_orders_dockerhub:
  extends: .deliver_dockerhub
  variables: *purchase_orders_service_variables
  needs:
    - job: build_purchase_orders_service
      artifacts: true
    - job: test_purchase_orders_service
      artifacts: false