.purchase_orders_service_variables: &purchase_orders_service_variables
  SERVICE_NAME: "purchase_orders_api"
  SERVICE_PATH: "sales/purchase_orders_service"

build_purchase_orders_service:
  extends: .build_service
  variables: *purchase_orders_service_variables

deliver_purchase_orders_dockerhub:
  extends: .deliver_dockerhub
  variables: *purchase_orders_service_variables
  needs:
    - job: build_purchase_orders_service
      artifacts: true

deploy_purchase_orders_prod:
  extends: .deploy_prod
  variables: *purchase_orders_service_variables
  needs:
    - job: deliver_purchase_orders_dockerhub
      artifacts: false
    - job: build_purchase_orders_service
      artifacts: true