.products_service_variables: &products_service_variables
  SERVICE_NAME: "products_api"
  SERVICE_PATH: "products/products_service"

build_products_service:
  extends: .build_service
  variables: *products_service_variables

test_products_service:
  extends: .test_service
  needs:
    - job: build_products_service
      artifacts: true

deliver_products_dockerhub:
  extends: .deliver_dockerhub
  variables: *products_service_variables
  needs:
    - job: build_products_service
      artifacts: true

deploy_products_prod:
  extends: .deploy_prod
  variables: *products_service_variables
  needs:
    - job: deliver_products_dockerhub
      artifacts: false
    - job: build_products_service
      artifacts: true
