.products_service_variables: &products_service_variables
  DOMAIN_PATH: "products"
  SERVICE_PATH: "products/products_service"
  SERVICE_NAME: "products_api"

build_products_service:
  extends: .build_service
  variables: *products_service_variables

test_products_service:
  extends: .test_service
  variables: *products_service_variables
  needs:
    - job: build_products_service
      artifacts: true

deliver_products_dockerhub:
  extends: .deliver_dockerhub
  variables: *products_service_variables
  needs:
    - job: build_products_service
      artifacts: true
    - job: test_products_service
      artifacts: false