build_users_service:
  stage: build
  tags:
    - dev
  variables:
    SERVICE_NAME: "users_api"
    SERVICE_PATH: "services/users_service"
  rules:
    - !reference [.rule_run_if_push_changes, rules]  
  before_script:
    - !reference [.create_and_export_service_images_variables]
  script:
    - docker build -t ${PROD_IMAGE} -f ${SERVICE_PATH}/users_api/Dockerfile.prod ${SERVICE_PATH}/users_api
    - !reference [.login_to_gitlab_registry]
    - docker push ${PROD_IMAGE}
  # artifacts:
  #   reports:
  #     dotenv: context.env
  needs:
    - job: preparation
      artifacts: true
