.users_service_variables: &users_service_variables
  SERVICE_NAME: "users_api"
  SERVICE_PATH: "services/users_service"

build_users_service:
  extends: .build_service
  variables: *users_service_variables

deliver_users_dockerhub:
  extends: .deliver_dockerhub
  variables: *users_service_variables
  needs:
    - job: build_users_service
      artifacts: true

deploy_users_prod:
  extends: .deploy_prod
  variables: *users_service_variables
  needs:
    - job: deliver_users_dockerhub
      artifacts: false
    - job: build_users_service
      artifacts: true
