.users_service_variables: &users_service_variables
  SERVICE_NAME: "users_api"
  SERVICE_PATH: "services/users_service"

build_users_service:
  extends: .build_service
  variables: *users_service_variables

deliver_users_dockerhub:
  extends: .deliver_dockerhub
  variables: *users_service_variables
