.category_service_variables: &category_service_variables
  SERVICE_NAME: "category_api"
  SERVICE_PATH: "services/category_service"

build_category_service:
  extends: .build_service
  variables: *category_service_variables

deliver_category_dockerhub:
  extends: .deliver_dockerhub
  variables: *category_service_variables
