.product_coordinator_service_variables: &product_coordinator_service_variables
  SERVICE_NAME: "product_coordinator_api"
  SERVICE_PATH: "products/product_coordinator_service"

build_product_coordinator_service:
  extends: .build_service
  variables: *product_coordinator_service_variables

deliver_product_coordinator_dockerhub:
  extends: .deliver_dockerhub
  variables: *product_coordinator_service_variables
  needs:
    - job: build_product_coordinator_service
      artifacts: true

deploy_product_coordinator_prod:
  extends: .deploy_prod
  variables: *product_coordinator_service_variables
  needs:
    - job: deliver_product_coordinator_dockerhub
      artifacts: false
    - job: build_product_coordinator_service
      artifacts: true