.product_coordinator_service_variables: &product_coordinator_service_variables
  DOMAIN_PATH: "products"
  SERVICE_PATH: "products/product_coordinator_service"
  SERVICE_NAME: "product_coordinator_api"

build_product_coordinator_service:
  extends: .build_service
  variables: *product_coordinator_service_variables

test_product_coordinator_service:
  extends: .test_service
  variables: *product_coordinator_service_variables
  needs:
    - job: build_product_coordinator_service
      artifacts: true

deliver_product_coordinator_dockerhub:
  extends: .deliver_dockerhub
  variables: *product_coordinator_service_variables
  needs:
    - job: build_product_coordinator_service
      artifacts: true
    - job: test_product_coordinator_service
      artifacts: false