.products_domain_variables: &products_domain_variables
  DOMAIN_PATH: "products"

deploy_prod_products_domain:
  extends: .deploy_prod
  variables: *products_domain_variables
  needs:
    - job: test_category_service
      optional: true
      artifacts: false
    - job: test_product_coordinator_service
      optional: true
      artifacts: false
    - job: test_products_service
      optional: true
      artifacts: false
    - job: test_tags_service
      optional: true
      artifacts: false
