.products_domain_variables: &products_domain_variables
  DOMAIN_PATH: "products"

deploy_prod_products_domain:
  extends: .deploy_prod
  variables: *products_domain_variables
  needs:
    - job: deliver_category_dockerhub
      optional: true
      artifacts: false
    - job: deliver_products_dockerhub
      optional: true
      artifacts: false
    - job: deliver_reviews_dockerhub
      optional: true
      artifacts: false
