.products_domain_variables: &products_domain_variables
  DOMAIN_PATH: "products"

deploy_prod_products_domain:
  extends: .deploy_prod
  variables: *products_domain_variables
  needs:
    - job: deliver_category_service_dockerhub
      optional: true
      artifacts: false
    - job: deliver_product_coordinator_service_dockerhub
      optional: true
      artifacts: false
    - job: deliver_products_service_dockerhub
      optional: true
      artifacts: false
    - job: deliver_tags_service_dockerhub
      optional: true
      artifacts: false
