version: "3.3"
services:
  category_api:
    image: ${CATEGORY_SERVICE_IMAGE}
    ports:
    - "5000:5000"
    restart: always
  product_coordinator_api:
    image: ${PRODUCT_COORDINATOR_SERVICE_IMAGE}
    ports:
    - "5001:5000"
    restart: always
  products_api:
    image: ${PRODUCTS_SERVICE_IMAGE}
    ports:
    - "5002:5000"
    restart: always
  reviews_api:
    image: ${REVIEWS_SERVICE_IMAGE}
    ports:
    - "5003:5000"
    restart: always
  tags_api:
    image: ${TAGS_SERVICE_IMAGE}
    ports:
    - "5004:5000"
    restart: always