version: "3.3"
services:
  category_api:
    container_name: category_api_${ENV}
    image: ${CATEGORY_SERVICE_IMAGE}
    profiles:
      - category_api
      - all
    ports:
      - "5000"
    restart: always
    environment:
      - SERVICE_NAME=category_api
    networks:
      - category
      - domain
  product_coordinator_api:
    container_name: product_coordinator_api_${ENV}
    image: ${PRODUCT_COORDINATOR_SERVICE_IMAGE}
    profiles:
      - product_coordinator_api
      - all
    ports:
      - "5000"
    restart: always
    environment:
      - SERVICE_NAME=product_coordinator_api
    networks:
      - product_coordinator
      - domain
  products_api:
    container_name: products_api_${ENV}
    image: ${PRODUCTS_SERVICE_IMAGE}
    profiles:
      - products_api
      - all
    ports:
      - "5000"
    restart: always
    environment:
      - SERVICE_NAME=products_api
    networks:
      - products
      - domain
  reviews_api:
    container_name: reviews_api_${ENV}
    image: ${REVIEWS_SERVICE_IMAGE}
    profiles:
      - reviews_api
      - all
    ports:
      - "5000"
    restart: always
    environment:
      - SERVICE_NAME=reviews_api
    networks:
      - reviews
      - domain
  tags_api:
    container_name: tags_api_${ENV}
    image: ${TAGS_SERVICE_IMAGE}
    profiles:
      - tags_api
      - all
    ports:
      - "5000"
    restart: always
    environment:
      - SERVICE_NAME=tags_api
    networks:
      - tags
      - domain

networks:
  category:
    name: category_api_${ENV}
    internal: true
  tags:
    name: tags_api_${ENV}
    internal: true
  reviews:
    name: reviews_api_${ENV}
    internal: true
  products:
    name: products_api_${ENV}
    internal: true
  product_coordinator:
    name: product_coordinator_api_${ENV}
    internal: true
  domain:
    name: products_${ENV}
