.users_service_variables: &users_service_variables
  DOMAIN_PATH: "users"
  SERVICE_PATH: "users/users_service"
  SERVICE_NAME: "users_api"

build_users_service:
  extends: .build_service
  variables: *users_service_variables

test_users_service:
  extends: .test_service
  variables: *users_service_variables
  needs:
    - job: build_users_service
      artifacts: true

deploy_qa_users_service:
  extends: .deploy_qa
  variables: *users_service_variables
  needs:
    - job: build_users_service
      artifacts: true
    - job: test_users_service
      artifacts: false

test_integration_and_functional_users_service:
  extends: .test_integration_and_functional_service
  variables: *users_service_variables
  needs:
    - job: build_users_service
      artifacts: true
    - job: deploy_qa_users_service
      artifacts: false
    - job: deploy_qa_api_gateway
      artifacts: false
      optional: true

deliver_users_dockerhub:
  extends: .deliver_dockerhub
  variables: *users_service_variables
  needs:
    - job: build_users_service
      artifacts: true
    - job: test_integration_and_functional_users_service
      artifacts: false
