.users_service_variables: &users_service_variables
  SERVICE_NAME: "users_api"
  SERVICE_PATH: "users/users_service"

build_users_service:
  extends: .build_service
  variables: *users_service_variables

test_users_service:
  extends: .test_service
  needs:
    - job: build_users_service
      artifacts: true

deliver_users_dockerhub:
  extends: .deliver_dockerhub
  variables: *users_service_variables
  needs:
    - job: build_users_service
      artifacts: true
    - job: test_users_service
      artifacts: false