# Pull base image
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ENV FLASK_DEBUG=1
ENV FLASK_ENV=development

# Add and install requirements
COPY --chown=python:python requirements.test.txt .
RUN python -m pip install -r requirements.test.txt

# Add app
COPY --chown=python:python src/tests tests

# Add coveragerc
COPY --chown=python:python .coveragerc .

# Add entrypoint.sh
COPY --chown=python:python src/.cicd/test.sh .
RUN chmod +x /usr/app/test.sh

CMD ["/usr/app/test.sh"]