FROM node:16-alpine as builder

WORKDIR /app

RUN npm install -g pnpm

COPY . .

RUN ls

RUN pnpm install --frozen-lockfile

RUN pnpm run build

FROM nginx:1.21.0-alpine
RUN mkdir /var/www/
COPY --from=builder /app/dist /var/www/dist
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

HEALTHCHECK CMD curl -f http://localhost:80 || exit 1

EXPOSE 80

