.reviews_service_variables: &reviews_service_variables
  SERVICE_NAME: "reviews_api"
  SERVICE_PATH: "services/reviews_service"

build_reviews_service:
  extends: .build_service
  variables: *reviews_service_variables

deliver_reviews_dockerhub:
  extends: .deliver_dockerhub
  variables: *reviews_service_variables
  needs:
    - job: build_reviews_service
      artifacts: true

deploy_reviews_prod:
  extends: .deploy_prod
  variables: *reviews_service_variables
  needs:
    - job: deliver_reviews_dockerhub
      artifacts: false
    - job: build_reviews_service
      artifacts: true