build_shopping_cart_service:
  stage: build
  tags:
    - dev
  variables:
    SERVICE_NAME: "shopping_cart_api"
    SERVICE_PATH: "services/shopping_cart_service"
  before_script:
    - !reference [.create_and_export_service_images_variables]
  script:
    - docker build -t ${PROD_IMAGE} -f ${SERVICE_PATH}/shopping_cart_api/Dockerfile.prod ${SERVICE_PATH}/shopping_cart_api
    - !reference [.login_to_gitlab_registry]
    - docker push ${PROD_IMAGE}
  # artifacts:
  #   reports:
  #     dotenv: context.env
  needs:
    - job: preparation
      artifacts: true
