.category_service_variables: &category_service_variables
  SERVICE_NAME: "category_api"
  SERVICE_PATH: "products/category_service"

build_category_service:
  extends: .build_service
  variables: *category_service_variables

test_category_service:
  extends: .test_service
  needs:
    - job: build_category_service
      artifacts: true
      

deliver_category_dockerhub:
  extends: .deliver_dockerhub
  variables: *category_service_variables
  needs:
    - job: build_category_service
      artifacts: true
    - job: test_category_service
      artifacts: false

deploy_category_prod:
  extends: .deploy_prod
  variables: *category_service_variables
  needs:
    - job: deliver_category_dockerhub
      artifacts: false
    - job: build_category_service
      artifacts: true
