.tags_service_variables: &tags_service_variables
  SERVICE_NAME: "tags_api"
  SERVICE_PATH: "products/tags_service"

build_tags_service:
  extends: .build_service
  variables: *tags_service_variables

test_tags_service:
  extends: .test_service
  needs:
    - job: build_tags_service
      artifacts: true

deliver_tags_dockerhub:
  extends: .deliver_dockerhub
  variables: *tags_service_variables
  needs:
    - job: build_tags_service
      artifacts: true

deploy_tags_prod:
  extends: .deploy_prod
  variables: *tags_service_variables
  needs:
    - job: build_tags_service
      artifacts: true
    - job: deliver_tags_dockerhub
      artifacts: false
